name: Clojure Tests

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Install dependencies
      run: lein deps

    - name: Run Clojure tests
      run: lein test
